# Generated by Django 4.2.2 on 2023-09-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemabio', '0006_alter_sesion_id_tipo_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='id_tipo_sesion',
            field=models.CharField(choices=[('1', 'FACIAL'), ('2', 'VOZ'), ('3', 'HUELLA'), ('4', 'NORMAL')], max_length=2),
        ),
    ]
