# Generated by Django 4.2.2 on 2023-09-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemabio', '0007_alter_sesion_id_tipo_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='id_tipo_sesion',
            field=models.CharField(choices=[('1', 'FACIAL'), ('2', 'VOZ'), ('3', 'HUELLA')], max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_actualizado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
